//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngineAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchEnginesList
    {
        public int Seid { get; set; }
        public string Source { get; set; }
        public string Domain { get; set; }
        public string Query { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Locale { get; set; }
        public string Geo_Location { get; set; }
        public string UULE { get; set; }
        public string Safe_Search { get; set; }
        public string Safe { get; set; }
        public string Device { get; set; }
        public string Results { get; set; }
        public string Provider { get; set; }
        public string tbm { get; set; }
        public string SEName { get; set; }
    }
}
